version: "3"

volumes:
  module_cache:

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:4000
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=beebeazdevassetst92p
      - AZURE_STORAGE_CONNECTION_STRING={AZURE_STORAGE_CONNECTION_STRING}
    volumes:
      - module_cache:/node_modules
