version: "3"

volumes:
  module_cache:

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:4000
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME={AZURE_STORAGE_ACCOUNT_NAME}
      - USER_ASSIGNED_MANAGED_IDENTITY_CLIENT_ID={USER_ASSIGNED_MANAGED_IDENTITY_CLIENT_ID}
    volumes:
      - module_cache:/node_modules
