version: "3"

volumes:
  module_cache:

services:
  app_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - AZURE_STORAGE_ACCOUNT_NAME={AZURE_STORAGE_ACCOUNT_NAME}
    volumes:
      - module_cache:/node_modules
    depends_on:
      - azurite

  app_release:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile.release
    ports:
      - 4000:4000
    environment:
      - PORT=4000

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
